# Generated by Django 2.2.6 on 2020-02-04 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmap', '0005_auto_20200204_1610'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tag_set',
            field=models.ManyToManyField(blank=True, to='bookmap.Tag'),
        ),
    ]
