# Generated by Django 2.2.11 on 2020-04-07 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_profile_tag_set'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='level',
        ),
    ]
