# Generated by Django 2.2.6 on 2020-01-31 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmap', '0002_auto_20200128_0054'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['-like', 'title']},
        ),
        migrations.AlterField(
            model_name='bookstore',
            name='name',
            field=models.CharField(default='storename', max_length=20, verbose_name='책방이름'),
        ),
    ]
