# Generated by Django 2.2.6 on 2020-03-06 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmap', '0006_auto_20200211_1519'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Crawling',
        ),
    ]
