# Generated by Django 2.2.6 on 2020-03-18 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmap', '0007_delete_crawling'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['title']},
        ),
        migrations.AlterField(
            model_name='bookstore',
            name='name',
            field=models.CharField(max_length=20, verbose_name='책방이름'),
        ),
        migrations.AlterField(
            model_name='bookstore',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='전화번호'),
        ),
    ]
