# Generated by Django 2.2.11 on 2020-03-23 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmap', '0008_auto_20200318_1304'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={},
        ),
    ]
