# Generated by Django 2.2.11 on 2020-04-08 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmap', '0009_auto_20200323_1227'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookstore',
            options={'ordering': ['bookstore_id']},
        ),
        migrations.AlterField(
            model_name='stamp',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
