# Generated by Django 2.2.11 on 2020-04-09 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmap', '0009_auto_20200323_1227'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookstore',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='bookstore',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
