# Generated by Django 2.2.11 on 2020-07-27 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmap', '0010_auto_20200409_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookstore',
            name='img',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
