# Generated by Django 2.2.11 on 2020-04-08 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmap', '0010_auto_20200408_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stamp',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
