# Generated by Django 3.0.2 on 2020-01-17 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookmap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Culture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('picture', models.ImageField(blank=True, upload_to='Culture/', verbose_name='이미지 등록')),
                ('start_time', models.DateField(verbose_name='시작 날짜')),
                ('finish_time', models.DateField(verbose_name='종료 날짜')),
                ('write_date', models.DateTimeField(auto_now=True, verbose_name='작성한 날짜')),
                ('content', models.TextField(verbose_name='내용')),
                ('group', models.CharField(choices=[('ET', '기타'), ('CO', '북콘서트'), ('ON', '원데이클래스'), ('CL', '소모임'), ('MO', '영화상영')], default='ET', max_length=7)),
                ('store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bookmap.BookStore')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('culture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='culture.Culture')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
